spring.application.name=mytogether-notification-worker
server.port=${PORT:8081}

# RabbitMQ Configuration
# Prioritizing RABBITMQ_PRIVATE_URL for internal Railway communication (zero egress fees)
# Prioritizing RABBITMQ_PRIVATE_URL for internal Railway communication (zero egress fees)
spring.rabbitmq.uri=${RABBITMQ_PRIVATE_URL:${RABBITMQ_URL}}


# Firebase Configuration
firebase.enabled=${FIREBASE_ENABLED:false}
firebase.config-path=${FIREBASE_CONFIG_PATH:firebase-service-account.json}
# Alternatively, if passing raw JSON via ENV
firebase.credentials-json=${FIREBASE_CREDENTIALS_JSON:}

spring.threads.virtual.enabled=true
logging.level.org.th.notification=DEBUG
